# Generated by Django 3.2.3 on 2021-05-19 13:43

from django.db import migrations, models
import django.db.models.deletion
import party_register.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_id', models.CharField(default=party_register.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PartyRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_username', models.CharField(max_length=100)),
                ('party_password', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='party_register.party')),
            ],
        ),
    ]
