# Generated by Django 3.2.3 on 2021-05-19 14:40

from django.db import migrations, models
import django.db.models.deletion
import party_register.utils


class Migration(migrations.Migration):

    dependencies = [
        ('party_register', '0003_auto_20210519_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(default=party_register.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
                ('isDeleted', models.CharField(default='N', max_length=1)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='party',
            name='isAdmin',
        ),
        migrations.AddField(
            model_name='party',
            name='isDeleted',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='party_register.admin')),
            ],
        ),
    ]
