# Generated by Django 3.2.3 on 2021-05-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_register', '0004_auto_20210519_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partyregister',
            old_name='party_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='partyregister',
            old_name='party_username',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='party',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
