# Generated by Django 3.2.3 on 2021-05-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_work', '0002_auto_20210521_1249'),
        ('party_register', '0005_auto_20210519_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminregister',
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='AdminRegister',
        ),
    ]
