# Generated by Django 3.2.3 on 2021-05-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party_register', '0004_auto_20210519_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('Item', models.CharField(max_length=30)),
                ('counts', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_to_date', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=30)),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='party_register.admin')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party_register.party')),
            ],
        ),
    ]
