# Generated by Django 3.2.3 on 2021-05-21 07:19

from django.db import migrations, models
import django.db.models.deletion
import party_register.utils


class Migration(migrations.Migration):

    dependencies = [
        ('admin_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(default=party_register.utils.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=10)),
                ('isDeleted', models.CharField(default='N', max_length=1)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_work.admin')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_work.admin'),
        ),
    ]
