# Generated by Django 3.2.3 on 2021-05-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_work', '0002_auto_20210521_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
