# Generated by Django 3.2.3 on 2021-05-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_work', '0003_alter_admin_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregister',
            old_name='Admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='adminregister',
            old_name='admin_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='adminregister',
            old_name='admin_username',
            new_name='username',
        ),
    ]
