# Generated by Django 3.2.3 on 2021-05-21 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_work', '0004_auto_20210521_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='Item',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='document',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_work.admin'),
        ),
    ]
