# Generated by Django 3.2.3 on 2021-05-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_work', '0005_auto_20210521_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='serial_number',
        ),
    ]
