# Generated by Django 3.2.3 on 2021-05-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_work', '0006_remove_document_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
